# Generated by Django 4.2.1 on 2023-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dep',
            field=models.CharField(default='General', max_length=10),
        ),
    ]
